# mysql
mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  database: machine_geek
# redis
redis:
  host: 127.0.0.1
  port: 6379
  password: 123456
  database: 0
## logback配置
logging:
  level:
    org:
      springframework:
        security: info
# 日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
