# mysql
mysql:
  host: 192.168.0.100
  port: 3306
  user: root
  password: 123456
# redis
redis:
  host: 192.168.0.100
  port: 6379
  password: 123456
  database: 0
## logback配置
logging:
  level:
    org:
      springframework:
        security: info