# 服务器
server:
  port: 8888
spring:
  # 配置文件
  profiles:
    active: dev
  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # Email配置
  mail:
    host: smtp.qq.com
    username: 794763733@qq.com
    password: soimybdqdxnxbcgc
  # FreeMarker
  freemarker:
    cache: false
    charset: UTF-8
    content-type: text/html
    template-loader-path: classpath:/templates/
    suffix: .ftl
    enabled: true
    request-context-attribute: req
    check-template-location: true
    expose-request-attributes: false
    expose-session-attributes: false
  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql.host}:${mysql.port}/${mysql.database}?useUnicode=true&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: ${mysql.user}
    password: ${mysql.password}
    # 连接池
    druid:
      # 最小空闲
      min-idle: 5
      # 最大存活连接
      max-active: 20
      # 初始化连接数
      initial-size: 5
      # 配置监控服务器
      stat-view-servlet:
        #是否允许开启监控
        enabled: true
        #是否允许重置监控数据
        reset-enable: true
        #druid访问路径
        url-pattern: /druid/*
      # 监控统计过滤器
      filters: stat,wall,log4j2
      # 检查关闭空闲连接的时间周期
      time-between-eviction-runs-millis: 6000
      # mergeSql，慢SQL记录
      connect-properties: druid.state.mergeSql=true
  # Redis
  redis:
    host: ${redis.host}
    port: ${redis.port}
    password: ${redis.password}
    database: ${redis.database}
# Mybatis Plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-enums-package: cn.machine.geek.enums
# Token超时时间（单位秒）
token:
  # 8个小时28800
  accessTokenExpire: 28800
  # 15天1296000
  refreshTokenExpire: 1296000
# 代码生成路径
generatePath: /Users/machine/Desktop/生成/
# 上传路径
upload:
  urlPath: /upload/
  localPath: /Volumes/Project/upload/